// See LICENSE for license details.
#ifndef _RISCV_AME_MEM_H
#define _RISCV_AME_MEM_H

#include "ame_unit.h"
#include "decode.h"
#include "decode_macros.h"
#include "mmu.h"
#include "trap.h"

#include <cstdint>


#include "ame_macc.h"

// ── element type tokens ────────────────────────────────────────────────────
#define AME_MATRIX_ELEMENT_TYPE_E8  uint8_t
#define AME_MATRIX_ELEMENT_TYPE_E16 uint16_t
#define AME_MATRIX_ELEMENT_TYPE_E32 uint32_t
#define AME_MATRIX_ELEMENT_TYPE_E64 uint64_t

#define AME_MATRIX_ELEMENT_TYPE_(TOKEN) AME_MATRIX_ELEMENT_TYPE_##TOKEN
#define AME_MATRIX_ELEMENT_TYPE(TOKEN)  AME_MATRIX_ELEMENT_TYPE_(TOKEN)

// ── role shape macros ──────────────────────────────────────────────────────
#define AME_MATRIX_ROWS_A(AMU) ((AMU).mtilem->read())
#define AME_MATRIX_COLS_A(AMU) ((AMU).mtilek->read())

#define AME_MATRIX_ROWS_B(AMU) ((AMU).mtilen->read())
#define AME_MATRIX_COLS_B(AMU) ((AMU).mtilek->read())

#define AME_MATRIX_ROWS_C(AMU) ((AMU).mtilem->read())
#define AME_MATRIX_COLS_C(AMU) ((AMU).mtilen->read())

// ── helper: A/B are NOT acc; C IS acc ──────────────────────────────────────
#define A_IS_ACC 0
#define B_IS_ACC 0
#define C_IS_ACC 1

// ── Memory proxy per element width ─────────────────────────────────────────
//
// Each AmeMatrixMemory<EW> wraps mmu_t and translates
//   Memory[addr]  →  mmu.load<ElementType>(addr)
//   Memory[addr] = val → mmu.store<ElementType>(addr, val)
// through an inline Ref object generated by the macro below.

#define AME_DECL_MEMORY_CLASS(EW, TYPE)                                        \
class AmeMatrixMemory##EW                                                      \
{                                                                              \
public:                                                                        \
  AmeMatrixMemory##EW(mmu_t& mmu) : mmu(mmu) {}                                \
  class Ref                                                                    \
  {                                                                            \
  public:                                                                      \
    Ref(mmu_t& mmu, reg_t addr) : mmu(mmu), addr(addr) {}                      \
    operator TYPE() const { return mmu.load<TYPE>(addr); }                     \
    Ref& operator=(TYPE val) { mmu.store<TYPE>(addr, val); return *this; }     \
  private:                                                                     \
    mmu_t& mmu;                                                                \
    reg_t addr;                                                                \
  };                                                                           \
  Ref operator[](reg_t addr) { return Ref(mmu, addr); }                        \
private:                                                                       \
  mmu_t& mmu;                                                                  \
};

AME_DECL_MEMORY_CLASS(E8,  uint8_t)
AME_DECL_MEMORY_CLASS(E16, uint16_t)
AME_DECL_MEMORY_CLASS(E32, uint32_t)
AME_DECL_MEMORY_CLASS(E64, uint64_t)

#undef AME_DECL_MEMORY_CLASS

#define AME_MATRIX_MEMORY_TYPE_E8  AmeMatrixMemoryE8
#define AME_MATRIX_MEMORY_TYPE_E16 AmeMatrixMemoryE16
#define AME_MATRIX_MEMORY_TYPE_E32 AmeMatrixMemoryE32
#define AME_MATRIX_MEMORY_TYPE_E64 AmeMatrixMemoryE64

// ── core: no require_matrix_ms / AME_END (for execute wrappers) ────────────
#define AME_MATRIX_MEM_CORE(ROL, EW, BODY)                                     \
  auto& AMU = p->AMU;                                                          \
  const reg_t rawReg = insn.m_md();                                            \
  if (ROL ## _IS_ACC) {                                                        \
    ame_require(rawReg >= 4 && rawReg < 8, insn);                              \
  } else {                                                                     \
    ame_require(rawReg < 4, insn);                                             \
  }                                                                            \
  const reg_t rows = AME_MATRIX_ROWS_##ROL(AMU);                               \
  const reg_t cols = AME_MATRIX_COLS_##ROL(AMU);                               \
  const reg_t base = RS1;                                                      \
  const reg_t stride = RS2;                                                    \
  const reg_t elementBytes = sizeof(AME_MATRIX_ELEMENT_TYPE(EW));              \
  MatrixReg& R = ROL ## _IS_ACC                                                \
    ? AMU.acc_regs[rawReg - 4]                                                 \
    : AMU.tile_regs[rawReg];                                                   \
  ame_require(rows <= R.get_rownum(), insn);                                   \
  ame_require(cols <= R.get_row_bytes() / elementBytes, insn);                 \
  AME_MATRIX_MEMORY_TYPE_##EW Memory(MMU);                                     \
  for (reg_t i = 0; i < rows; ++i) {                                           \
    for (reg_t j = 0; j < cols; ++j) {                                          \
      AME_MATRIX_ELEMENT_TYPE(EW)& Rij =                                       \
          R.elt<AME_MATRIX_ELEMENT_TYPE(EW)>(i, j);                            \
      BODY;                                                                    \
    }                                                                          \
  }

// ── full wrapper: require_matrix_ms + core + AME_END (for insns/*.h) ───────
#define AME_MATRIX_MEM_IMPL(ROL, EW, BODY)                                     \
  do {                                                                         \
    require_matrix_ms;                                                         \
    AME_MATRIX_MEM_CORE(ROL, EW, BODY);                                        \
    AME_END;                                                                   \
  } while (0);

// ── public per-instruction macros (48 total) ───────────────────────────────

// -- A normal load --
#define AME_MATRIX_LOAD_A_E8_NORMAL(BODY)  AME_MATRIX_MEM_IMPL(A, E8, BODY)
#define AME_MATRIX_LOAD_A_E16_NORMAL(BODY) AME_MATRIX_MEM_IMPL(A, E16, BODY)
#define AME_MATRIX_LOAD_A_E32_NORMAL(BODY) AME_MATRIX_MEM_IMPL(A, E32, BODY)
#define AME_MATRIX_LOAD_A_E64_NORMAL(BODY) AME_MATRIX_MEM_IMPL(A, E64, BODY)

// -- B normal load --
#define AME_MATRIX_LOAD_B_E8_NORMAL(BODY)  AME_MATRIX_MEM_IMPL(B, E8, BODY)
#define AME_MATRIX_LOAD_B_E16_NORMAL(BODY) AME_MATRIX_MEM_IMPL(B, E16, BODY)
#define AME_MATRIX_LOAD_B_E32_NORMAL(BODY) AME_MATRIX_MEM_IMPL(B, E32, BODY)
#define AME_MATRIX_LOAD_B_E64_NORMAL(BODY) AME_MATRIX_MEM_IMPL(B, E64, BODY)

// -- C normal load --
#define AME_MATRIX_LOAD_C_E8_NORMAL(BODY)  AME_MATRIX_MEM_IMPL(C, E8, BODY)
#define AME_MATRIX_LOAD_C_E16_NORMAL(BODY) AME_MATRIX_MEM_IMPL(C, E16, BODY)
#define AME_MATRIX_LOAD_C_E32_NORMAL(BODY) AME_MATRIX_MEM_IMPL(C, E32, BODY)
#define AME_MATRIX_LOAD_C_E64_NORMAL(BODY) AME_MATRIX_MEM_IMPL(C, E64, BODY)

// -- A normal store --
#define AME_MATRIX_STORE_A_E8_NORMAL(BODY)  AME_MATRIX_MEM_IMPL(A, E8, BODY)
#define AME_MATRIX_STORE_A_E16_NORMAL(BODY) AME_MATRIX_MEM_IMPL(A, E16, BODY)
#define AME_MATRIX_STORE_A_E32_NORMAL(BODY) AME_MATRIX_MEM_IMPL(A, E32, BODY)
#define AME_MATRIX_STORE_A_E64_NORMAL(BODY) AME_MATRIX_MEM_IMPL(A, E64, BODY)

// -- B normal store --
#define AME_MATRIX_STORE_B_E8_NORMAL(BODY)  AME_MATRIX_MEM_IMPL(B, E8, BODY)
#define AME_MATRIX_STORE_B_E16_NORMAL(BODY) AME_MATRIX_MEM_IMPL(B, E16, BODY)
#define AME_MATRIX_STORE_B_E32_NORMAL(BODY) AME_MATRIX_MEM_IMPL(B, E32, BODY)
#define AME_MATRIX_STORE_B_E64_NORMAL(BODY) AME_MATRIX_MEM_IMPL(B, E64, BODY)

// -- C normal store --
#define AME_MATRIX_STORE_C_E8_NORMAL(BODY)  AME_MATRIX_MEM_IMPL(C, E8, BODY)
#define AME_MATRIX_STORE_C_E16_NORMAL(BODY) AME_MATRIX_MEM_IMPL(C, E16, BODY)
#define AME_MATRIX_STORE_C_E32_NORMAL(BODY) AME_MATRIX_MEM_IMPL(C, E32, BODY)
#define AME_MATRIX_STORE_C_E64_NORMAL(BODY) AME_MATRIX_MEM_IMPL(C, E64, BODY)

// -- A transposed load --
#define AME_MATRIX_LOAD_A_E8_TRANSPOSED(BODY)  AME_MATRIX_MEM_IMPL(A, E8, BODY)
#define AME_MATRIX_LOAD_A_E16_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(A, E16, BODY)
#define AME_MATRIX_LOAD_A_E32_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(A, E32, BODY)
#define AME_MATRIX_LOAD_A_E64_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(A, E64, BODY)

// -- B transposed load --
#define AME_MATRIX_LOAD_B_E8_TRANSPOSED(BODY)  AME_MATRIX_MEM_IMPL(B, E8, BODY)
#define AME_MATRIX_LOAD_B_E16_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(B, E16, BODY)
#define AME_MATRIX_LOAD_B_E32_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(B, E32, BODY)
#define AME_MATRIX_LOAD_B_E64_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(B, E64, BODY)

// -- C transposed load --
#define AME_MATRIX_LOAD_C_E8_TRANSPOSED(BODY)  AME_MATRIX_MEM_IMPL(C, E8, BODY)
#define AME_MATRIX_LOAD_C_E16_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(C, E16, BODY)
#define AME_MATRIX_LOAD_C_E32_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(C, E32, BODY)
#define AME_MATRIX_LOAD_C_E64_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(C, E64, BODY)

// -- A transposed store --
#define AME_MATRIX_STORE_A_E8_TRANSPOSED(BODY)  AME_MATRIX_MEM_IMPL(A, E8, BODY)
#define AME_MATRIX_STORE_A_E16_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(A, E16, BODY)
#define AME_MATRIX_STORE_A_E32_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(A, E32, BODY)
#define AME_MATRIX_STORE_A_E64_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(A, E64, BODY)

// -- B transposed store --
#define AME_MATRIX_STORE_B_E8_TRANSPOSED(BODY)  AME_MATRIX_MEM_IMPL(B, E8, BODY)
#define AME_MATRIX_STORE_B_E16_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(B, E16, BODY)
#define AME_MATRIX_STORE_B_E32_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(B, E32, BODY)
#define AME_MATRIX_STORE_B_E64_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(B, E64, BODY)

// -- C transposed store --
#define AME_MATRIX_STORE_C_E8_TRANSPOSED(BODY)  AME_MATRIX_MEM_IMPL(C, E8, BODY)
#define AME_MATRIX_STORE_C_E16_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(C, E16, BODY)
#define AME_MATRIX_STORE_C_E32_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(C, E32, BODY)
#define AME_MATRIX_STORE_C_E64_TRANSPOSED(BODY) AME_MATRIX_MEM_IMPL(C, E64, BODY)

// ── execute wrapper declarations (48) ──────────────────────────────────────
#define AME_MATRIX_DECL_EXECUTE(NAME)                                          \
  void execute_##NAME(processor_t* p, insn_t insn);

// A normal load
AME_MATRIX_DECL_EXECUTE(mlae8)
AME_MATRIX_DECL_EXECUTE(mlae16)
AME_MATRIX_DECL_EXECUTE(mlae32)
AME_MATRIX_DECL_EXECUTE(mlae64)
// B normal load
AME_MATRIX_DECL_EXECUTE(mlbe8)
AME_MATRIX_DECL_EXECUTE(mlbe16)
AME_MATRIX_DECL_EXECUTE(mlbe32)
AME_MATRIX_DECL_EXECUTE(mlbe64)
// C normal load
AME_MATRIX_DECL_EXECUTE(mlce8)
AME_MATRIX_DECL_EXECUTE(mlce16)
AME_MATRIX_DECL_EXECUTE(mlce32)
AME_MATRIX_DECL_EXECUTE(mlce64)
// A normal store
AME_MATRIX_DECL_EXECUTE(msae8)
AME_MATRIX_DECL_EXECUTE(msae16)
AME_MATRIX_DECL_EXECUTE(msae32)
AME_MATRIX_DECL_EXECUTE(msae64)
// B normal store
AME_MATRIX_DECL_EXECUTE(msbe8)
AME_MATRIX_DECL_EXECUTE(msbe16)
AME_MATRIX_DECL_EXECUTE(msbe32)
AME_MATRIX_DECL_EXECUTE(msbe64)
// C normal store
AME_MATRIX_DECL_EXECUTE(msce8)
AME_MATRIX_DECL_EXECUTE(msce16)
AME_MATRIX_DECL_EXECUTE(msce32)
AME_MATRIX_DECL_EXECUTE(msce64)
// A transposed load
AME_MATRIX_DECL_EXECUTE(mlate8)
AME_MATRIX_DECL_EXECUTE(mlate16)
AME_MATRIX_DECL_EXECUTE(mlate32)
AME_MATRIX_DECL_EXECUTE(mlate64)
// B transposed load
AME_MATRIX_DECL_EXECUTE(mlbte8)
AME_MATRIX_DECL_EXECUTE(mlbte16)
AME_MATRIX_DECL_EXECUTE(mlbte32)
AME_MATRIX_DECL_EXECUTE(mlbte64)
// C transposed load
AME_MATRIX_DECL_EXECUTE(mlcte8)
AME_MATRIX_DECL_EXECUTE(mlcte16)
AME_MATRIX_DECL_EXECUTE(mlcte32)
AME_MATRIX_DECL_EXECUTE(mlcte64)
// A transposed store
AME_MATRIX_DECL_EXECUTE(msate8)
AME_MATRIX_DECL_EXECUTE(msate16)
AME_MATRIX_DECL_EXECUTE(msate32)
AME_MATRIX_DECL_EXECUTE(msate64)
// B transposed store
AME_MATRIX_DECL_EXECUTE(msbte8)
AME_MATRIX_DECL_EXECUTE(msbte16)
AME_MATRIX_DECL_EXECUTE(msbte32)
AME_MATRIX_DECL_EXECUTE(msbte64)
// C transposed store
AME_MATRIX_DECL_EXECUTE(mscte8)
AME_MATRIX_DECL_EXECUTE(mscte16)
AME_MATRIX_DECL_EXECUTE(mscte32)
AME_MATRIX_DECL_EXECUTE(mscte64)

#undef AME_MATRIX_DECL_EXECUTE

#endif
